const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  loadFolder: (dir, root) => ipcRenderer.invoke('load-folder', dir, root),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  getAppVersion: () => ipcRenderer.invoke('get-version'),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  downloadDependency: (which) => ipcRenderer.invoke('download-dependency', which),
  checkDependencies: () => ipcRenderer.invoke('check-dependencies'),
  onThemeChanged: (cb) => ipcRenderer.on('theme-changed', (e, t) => cb(t)),
  onTreeStart: (cb) => ipcRenderer.on('tree-start', (e, data) => cb(data)),
  onTreeNode: (cb) => ipcRenderer.on('tree-node', (e, data) => cb(data)),
  onTreeEnd: (cb) => ipcRenderer.on('tree-end', (e, parent) => cb(parent)),
  onLoadProgress: (cb) => ipcRenderer.on('load-progress', (e, data) => cb(data)),
  minimize: () => ipcRenderer.send('window-control', 'minimize'),
  maximize: () => ipcRenderer.send('window-control', 'maximize'),
  close: () => ipcRenderer.send('window-control', 'close'),
  startParse: (data) => ipcRenderer.invoke('start-parse', data),
  onParseProgress: (cb) => ipcRenderer.on('parse-progress', (e, msg) => cb(msg)),
  onParseStep: (cb) => ipcRenderer.on('parse-step', (e, data) => cb(data)),
  onParseComplete: (cb) => ipcRenderer.on('parse-complete', (e, success) => cb(success)),
  openParsedFolder: () => ipcRenderer.invoke('open-parsed-folder'),
  cancelParse: () => ipcRenderer.send('cancel-parse'),
  openParserFolder: (which) => ipcRenderer.invoke('open-parser-folder', which),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  showUpdatePrompt: () => ipcRenderer.invoke('show-update-prompt'),
  onShowUpdateNotice: (cb) => ipcRenderer.on('show-update-notice', () => cb()),
  onHideUpdateNotice: (cb) => ipcRenderer.on('hide-update-notice', () => cb()),
  performUpdate: () => ipcRenderer.invoke('perform-update'),
  updateLater: () => ipcRenderer.send('update-later'),
  updateDownloaded: () => ipcRenderer.send('update-downloaded'),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, data) => cb(data))
});
